openapi: 3.0.0
info:
  description: This API provides audit info
  version: "1.0.0"
  title: Audit API
  contact:
    email: jaspreetsdhunna@gmail.com
paths:
  /membership:
    get:
      summary: gets a membership request from history
      operationId: app.get_gym_member
      description: Gets membership request from the gym event store
      parameters:
        - name: index
          in: query
          description: Gets the gym member at the index in the gym event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a membership event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/MembershipItem'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /pt-session:
    get:
      summary: gets a pt-session request from history
      operationId: app.get_pt_session
      description: Gets pt-session request from the gym event store
      parameters:
        - name: index
          in: query
          description: Gets the pt session request at the index in the gym event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a pt session event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/PtItem'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found  
components:
  schemas:
    MembershipItem:
      type: object
      required:
        - user_info
        - membership_months
        - start_date
        - gym_address
        - timestamp
      properties:
        user_info:
          $ref: '#/components/schemas/User'
        membership_months:
          type: integer
          format: int32
          example: 12
        start_date:
          type: string
          format: date
          example: '2017-07-21'
        gym_address: 
          type: string
          example: '13999 88 ave, Burnaby'
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        
    PtItem:
      type: object
      required:
        - user_info
        - trainer_id
        - start_time
        - duration_hours
        - timestamp
      properties:
        user_info:
          $ref: '#/components/schemas/User'
        trainer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        start_time:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        duration_hours:
          type: number
          format: float
          example: 1.5
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    User:
      required:
        - user_id
        - user_name
        - user_height
        - user_weight
        - user_address
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        user_name:
          type: string
          example: 'Jack'
        user_height:
          type: number
          format: float
          example: 180.5
        user_weight:
          type: number
          format: float
          example: 200.8
        user_address:
          type: string
          example: '13999 88 ave, Burnaby'
      type: object